### ISSUE TITLE
First run of snotelr fails (dependencies)

### ISSUE THREAD

**Issue by JepsonNomad** [bluegreen-labs/snotelr#16]
Hi there, just using snotelr for the first time here; looks like an awesome package. I ran into a first-install issue that may be pertinent for other users.

```
R version 4.1.2 (2021-11-01)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.0.1
```

The following ran fine in R, except for a console output warning that I didn't have the foresight to copy. And, more importantly, the new window that opened in my browser gave a "dashboard header" error and failed to produce the map/plot GUI. 

```
install.packages("snotelr")
library(snotelr)
snotel_explorer()
```

I had to install 3 additional packages before the explorer worked on my browser:

```
install.packages(c("shinydashboard", "plotly", "leaflet"))
```

Once those were installed, all was good. Seems like these should be dependencies, rather than suggests.

**Comment by khufkens** [comment]
Hi @JepsonNomad 

Thanks for bringing this to my attention.

CRAN (who curates packages) has strong limits on the number of dependencies on other packages. Including the interface components sadly tips the scales, as well as bump additional dependencies of those packages.

I've fixed this in the documentation on the main page so people are sure to install additional components.

A recent update also ensures the message you've seen flash by isn't ignored, and the interface is not loaded. However this hasn't made it to CRAN yet.

For the latest release you can always install from github itself, but since you figured things out you are set.

Good luck with your analysis!
